<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="css/footer.css" rel="stylesheet">


<!--footer-->
<footer>
    <div class="footer_top">
        <div class="container">
            <div class="col-md-12 bagcgrey">
                <div class="row">
                    <div class="methodh4">
                        <h4>FOLLOW US</h4>
                    </div>
                    <ul class="social socmatpbo">
                        <p></p>
                        <li><a target="_blank" href="https://www.facebook.com/imageeditingservice"><i class="fa fa-facebook"></i></a></li>
                        <li><a target="_blank" href="https://twitter.com/imageeditingi2v"><i class="fa fa-twitter"></i></a></li>
                        <li><a target="_blank" href="https://www.linkedin.com/company/image2vectorgraphicsindia"><i class="fa fa-linkedin"></i></a></li>
                        <li><a target="_blank" href="https://plus.google.com/+Image2vectorgraphicsIndia9"><i class="fa fa-google-plus"></i></a></li>
                        <li><a target="_blank" href="https://www.pinterest.com/imageediting/"><i class="fa fa-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_bottom_col">
        <div class="container">
            <div class="col-md-7">
                <div class="row">
                    <div class="col-md-4">
                        <div class="heading_footer">Image <span>Processing</span> </div>
                        <ul class="footerul">
                            <li><a title="Image Processing Services" href="image_processing_india.html">Image Processing Services</a></li>
                            <li><a title="Image Background Cleaning" href="image_background_cleaning_india.html">Image Background Cleaning </a></li>
                            <li><a title="Image Masking Service" href="image_masking_india.html">Image Masking Service </a></li>
                            <li><a title="Image Clipping Path" href="image_clipping_path_india.html">Image Clipping Path</a></li>
                            <li><a title="Image Retouching" href="image_retouching_india.html">Image Retouching</a></li>
                            <li><a title="Image Background Removal" href="image_background_removal.html">Image Background Removal</a></li>
                            <li><a title="Image Resizing Service" href="image_resizing_india.html">Image Resizing Service</a></li>
                            <li><a title="Image Cut Out Service" href="image-cut-out-service.html">Image Cut Out Service</a></li>
                            <li><a title="Product Image Retouching Service" href="product-image-retouching-service.html">Product Image Retouching Service</a></li>
                            <li><a title="Catalog Image Editing" href="catalog-image-editing.html">Catalog Image Editing</a></li>
                            <li><a title="Digital Image Processing" href="digital-image-processing.html">Digital Image Processing</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <div class="heading_footer">Graphic <span>Design</span> </div>
                        <ul class="footerul">
                            <li class="home">Graphic Design</li>
                            <li><a title="Graphic Designing" href="graphic_designing_services.html">Graphic Designing</a></li>
                            <li><a title="Website Designing" href="website_designing_india.html">Website Designing</a></li>
                            <li><a title="Flash, GIF Banner Creation" href="flash_gif_banner_creation_india.html">Flash / GIF Banner Creation</a></li>
                            <li><a title="PowerPoint Presentations" href="powerpoint_presentations_india.html">PowerPoint Presentations</a></li>
                            <li><a title="Logo Designing" href="logo_designing_india.html">Logo Designing</a></li>
                            <li><a title="Brochure Design" href="brochure-designing.html">Brochure Design</a></li>
                            <li><a title="Emailer Design" href="emailer_design_india.html">Emailer Design</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <div class="heading_footer">Photo <span>Editing</span> </div>
                        <ul class="footerul">
                            <li><a href="photo_restoration_india.html" title="Photo Restoration">Photo Restoration</a></li>
                            <li><a href="photo_enhancement_india.html" title="Photo Enhancement">Photo Enhancement</a></li>
                            <li><a href="photo_color_correction.html" title="Color Correction">Color Correction</a></li>
                            <li><a href="photo_editing_india.html" title="Photo Editing">Photo Editing</a></li>
                            <li><a href="panorama-photo-stitching.html" title="Panorama Photo Stitching">Panorama Photo Stitching</a></li>
                            <li><a href="wedding-photo-editing.html" title="Wedding Photo Editing">Wedding Photo Editing</a></li>
                            <li><a href="real-estate-virtual-tour.html" title="Real Estate Virtual Tour">Real Estate Virtual Tour</a></li>
                            <li><a href="real-estate-hdr-photo-editing.html" title="Real Estate HDR Photo Editing">Real Estate HDR Photo Editing</a></li>
                            <li><a href="real-estate-image-editing-services.html" title="Real Estate Image Editing">Real Estate Image Editing</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="heading_footer">Online Store <span>Product Editing</span> </div>
                            <ul class="footerul">
                                <li><a href="product-image-editing-services.html" title="Prodcut Image Editing">Product Image Editing</a></li>
                                <li><a href="image-watermark-removal-service.html" title="Image Watermark Removal">Watermark Removal</a></li>
                                <li><a href="fashion-glamour-apparel-photo-editing.html" title="Fashion Apparel Photo Editing">Fashion Apparel Photo Editing</a></li>
                                <li><a href="jewellery-image-editing.html" title="Jewellery Photo Editing">Jewellery Photo Editing</a></li>
                                <li><a href="ecommerce-store-image-management.html" title="Ecommerce Store Image Management">Ecommerce Store Image Management</a></li>
                            </ul>
                            <div class="heading_footer">Vector <span>Conversion</span> </div>
                            <ul class="footerul">
                                <li><a href="image_vector_conversion_services.html" title="Image to Vector Conversion">Image to Vector Conversion</a></li>
                                <li><a href="vector-art-conversion-services.html" title="Vector Art Conversion Services">Vector Art Conversion Services</a></li>
                                <li><a href="convert-logo-to-vector.html" title="Convert Logo to vector">Convert Logo to vector</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="heading_footer">Contact <span>us</span> </div>
                            <ul class="footerul">
                                <p>To contact us send an email directly to <a href="mailto:webenlance@gmail.com">webenlance@gmail.com</a> use this</p>
                                <p> Call us at<b>+91 9999878398</b></p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


<div class="copyright">
    <p>Copyright © 2016 webenlance. Terms & Condition | <a href="sitemap.html">Sitemap</a> | <a href="sitemap.xml">Sitemap xml</a></p>
</div>