<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="css/footer.css" rel="stylesheet">


<!--footer-->
<footer>
    <div class="footer_top">
        <div class="container">
            <div class="col-md-12 bagcgrey">
                <div class="row">
                    <div class="methodh4">
                        <h4>BİZİ TAKİP EDİN</h4>
                    </div>
                    <ul class="social socmatpbo">
                        <p></p>
                        <li><a target="_blank" href="https://www.facebook.com/imageeditingservice"><i class="fa fa-facebook"></i></a></li>
                        <li><a target="_blank" href="https://twitter.com/imageeditingi2v"><i class="fa fa-twitter"></i></a></li>
                        <li><a target="_blank" href="https://www.linkedin.com/company/image2vectorgraphicsindia"><i class="fa fa-linkedin"></i></a></li>
                        <li><a target="_blank" href="https://plus.google.com/+Image2vectorgraphicsIndia9"><i class="fa fa-google-plus"></i></a></li>
                        <li><a target="_blank" href="https://www.pinterest.com/imageediting/"><i class="fa fa-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_bottom_col">
        <div class="container">
            <div class="col-md-7">
                <div class="row">
                    <div class="col-md-4">
                        <div class="heading_footer">Kullanıcı <span>İşlemleri</span> </div>
                        <ul class="footerul">
                            <li><a title="Image Processing Services" href="image_processing_india.html">Üye Ol </a></li>
                            <li><a title="Image Background Cleaning" href="image_background_cleaning_india.html">Üye Girişi </a></li>
                            <li><a title="Image Masking Service" href="image_masking_india.html">Sepet </a></li>
                            <li><a title="Image Clipping Path" href="image_clipping_path_india.html">Ürün Sat </a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <div class="heading_footer">Yardım<span>Bilgileri</span>  </div>
                        <ul class="footerul">
                            <li><a title="Graphic Designing" href="graphic_designing_services.html">Nasıl Sipariş Veririm? </a></li>
                            <li><a title="Website Designing" href="website_designing_india.html">Nasıl Satış Yaparım? </a></li>
                            <li><a title="Flash, GIF Banner Creation" href="flash_gif_banner_creation_india.html">Nasıl Kayıt Olurum? </a></li>
                            <li><a title="PowerPoint Presentations" href="powerpoint_presentations_india.html">Nasıl Satış Yaparım? </a></li>
                            <li><a title="Logo Designing" href="logo_designing_india.html">Profilime Nasıl Bakarım? </a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <div class="heading_footer">Pinti.com <span>Hakkında</span> </div>
                        <ul class="footerul">
                            <li><a href="photo_restoration_india.html" title="Photo Restoration">Hakkında</a></li>
                            <li><a href="photo_enhancement_india.html" title="Photo Enhancement">Proje Hakkında</a></li>
                            <li><a href="photo_color_correction.html" title="Color Correction">Takım Hakkında</a></li>
                            <li><a href="photo_editing_india.html" title="Photo Editing">Rapor</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="heading_footer">Kategori <span>Bilgileri</span> </div>
                            <ul class="footerul">
                                <li><a href="product-image-editing-services.html" title="Prodcut Image Editing">Giyim & Ayakkabı</a></li>
                                <li><a href="image-watermark-removal-service.html" title="Image Watermark Removal">Elektronik</a></li>
                                <li><a href="fashion-glamour-apparel-photo-editing.html" title="Fashion Apparel Photo Editing">Ev, Bahçe, Ofis</a></li>
                                <li><a href="jewellery-image-editing.html" title="Jewellery Photo Editing">Spor & Outdoor</a></li>
                                <li><a href="ecommerce-store-image-management.html" title="Ecommerce Store Image Management">Hobi, Eğlence ve Sanat</a></li>
                                <li><a href="jewellery-image-editing.html" title="Jewellery Photo Editing">Kişisel Bakım & Kozmetik</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="heading_footer">İletişim <span>Bilgileri</span> </div>
                            <ul class="footerul">
                                <p>Bizimle iletişim kurmak ve email atmak için <a href="mailto:pintiproject@gmail.com">pinti@gmail.com</a> adresini kullanabilirsiniz.</p>
                                <p>Bizi arayın: <b>+90 222 222 22 22</b></p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


<div class="copyright">
    <p>Copyright © 2016 webenlance. Terms & Condition | <a href="sitemap.html">Sitemap</a> | <a href="sitemap.xml">Sitemap xml</a></p>
</div>