<div id="header">
    <a href="<?php
    require_once "../model/Constants.php";
    require_once "../controller/session.php";
    echo Constants::$serverUrl;
    ?>"><img id="logo" align="left" src="img/logo.png" width="10%" alt="pinti.com"/></a>
    <?php
    $product_count=0;
    if(isset($_COOKIE['product'])){
        $product_count=count($_COOKIE['product']);
    }

    if(!$_SESSION["isLogged"]) {
        echo "       
            <ul >
                <li ><a href = 'signin' > Üye ol </a ></li >
                <li ><a href = 'login'> Giriş yap </a ></li >
                <li ><a href = 'sell' > Ürün Sat </a ></li >
                <li ><a href = 'help' > Yardım</a ></li >
                <li ><a href = 'bilgilendirme/index.html' > Hakkında</a ></li >
                <li ><a href = 'sepet'> Sepet (".$product_count.")</a ></li >
            </ul >";
    }
    else{
        echo "
            <ul >
                <li><label>Hoşgeldin <a href='profile?userid=".$_SESSION['id']."'>".$_SESSION['username']."</a></label></li>
                <li ><a href = 'sell' > Ürün Sat </a ></li >
                <li ><a href = 'help' > Yardım</a ></li >
                <li><a href = 'inbox'>Mesajlaşma</a></li>
                <li ><a href = 'bilgilendirme/index.html' > Hakkında</a ></li >
                <li ><a href = 'sepet'> Sepet (".$product_count.")</a ></li >
                 <li ><a href = 'logout' > Çıkış yap </a ></li >
                 
            </ul >
            " ;
    }
    ?>
</div>