<?php
ob_start();
header('content-type: text/html; charset=utf8');
?>
    <!DOCTYPE HTML>
    <html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <title>Pinti.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link rel="stylesheet" type="text/css" href="dist/css/bootstrap.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    </head>
    <body>
<?php
require_once "common/header.phtml";
?>

<div class="row">
    <div class="col-md-4 col-md-offset-4" style="margin-top: 15px;">
        <form class="form-horizontal" role="form">
            <fieldset>
                <!-- Form Name -->
                <legend>Addres Bilgileri</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Adres Başlığı</label>
                    <div class="col-sm-10">
                        <input type="text" placeholder="Ör: Ev Adresim" class="form-control">
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Ad</label>
                    <div class="col-sm-10">
                        <input type="text" placeholder="" class="form-control">
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Soyad</label>
                    <div class="col-sm-10">
                        <input type="text" placeholder="" class="form-control">
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Şehir</label>
                    <div class="col-sm-10">
                        <input type="text"  class="form-control">
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">İlçe</label>
                    <div class="col-sm-10">
                        <input type="text"  class="form-control">
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Adres</label>
                    <div class="col-sm-10">
                        <textarea rows="4" cols="50" class="form-control">

                        </textarea>
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Posta Kodu</label>
                    <div class="col-sm-10">
                        <input type="text"  class="form-control">
                    </div>
                </div>


                <!-- Text input-->
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Cep Telefonu</label>

                    <div class="col-sm-10">
                        <input type="text"  placeholder="05XX XXX XX XX" class="form-control">
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-default">Vazgeç</button>
                            <button type="button" onClick="location.href='odeme'" class="btn btn-primary">Kaydet ve Devam Et</button>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div><!-- /.col-lg-12 -->
</div><!-- /.row -->

<?php require_once "common/footer.phtml"; ?>
</body>
</html>