<?php
/**
 * Created by PhpStorm.
 * User: oguz
 * Date: 8.10.2016
 * Time: 14:12
 */?>
<?php
require_once "../controller/session.php";
require_once "common/header.phtml"; ?>
<html>
    <head>
        <title>Yardım</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="css/style.css"/>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" type="text/css" href="dist/css/bootstrap.css">
        <!-- Custom styles for this template -->
        <!link href="navbar.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="css/menubar.css"/>
        <!link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
        <h2>Yardım</h2>
        <p>Yardım sayfası</p>
    </body>
</html>
