<html>
    <head>
        <title>Giriş Yap</title>
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <script type="text/javascript" src="js/submit.js"></script>
    </head>
    <body>
    <script>
        window.fbAsyncInit = function() {
            FB.init({
                appId      : '1321780007845681',
                xfbml      : true,
                version    : 'v2.8'
            });
            FB.AppEvents.logPageView();
        };
        function myFacebookLogin() {
        FB.getLoginStatus(function(response) {
            if (response.status === 'connected') {
                console.log('Logged in.');
                FB.api(
                    '/me',
                    {fields: 'id,first_name,last_name,email'}, function(response){

                    //Post edilecek parametreler
                        params = new Array();
                        params["firstName"] = response.first_name;
                        params["lastName"]=response.last_name;
                        params["email"]=response.email;
                        params["password"]=null;
                        params["facebookID"]=response.id;
                        params["signType"]="fb";

                     /* var form = document.createElement("form");
                        form.setAttribute("method","post");
                        var hiddenField = document.createElement("input");
                        hiddenField.setAttribute("type","hidden");
                        hiddenField.setAttribute("name","email");
                        hiddenField.setAttribute("value",response.email);

                        form.appendChild(hiddenField);

                        document.body.appendChild(form);
                        form.submit();
                        */

                    //Javascript kullanarak post yapan method..
                    submit("login",params,"post");
                });
            }
            else {
                FB.login(function(response){
                }, {scope: 'public_profile,email'});
            }
        });
        }
        (function(d, s, id){
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {return;}
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));


    </script>
    <div class="authForm">
        <h1 class="authBaslik">Giriş Yap</h1>
        <div class="faux-fb-btn">
            <button onclick="myFacebookLogin()">Facebook ile giriş yap</button>
        </div>
        <h5>veya</h5>
        <form method="post" id="loginForm">

            <table>
                <tr>
                    <td><label>E-posta adresiniz:</label></td>
                    <td><input class="txtBox" type="email" name="email" placeholder="e-mail" </td>
                </tr>
                <tr>
                    <td><label>Şifreniz:</label></td>
                    <td><input class="txtBox" type="password" name="password" placeholder="password"></td>
                </tr>
                <tr>
                    <td><a href="../sifremi_unuttum.php"><label>Şifremi unuttum.</label></a></td>
                    <td><input type="submit" name="btnLogin" value="Giriş Yap"></td>
                </tr>
            </table>
        </form>
    </div>
    </body>
</html>
