<?php
ob_start();
header('content-type: text/html; charset=utf8');
?>
<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Pinti.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="dist/css/bootstrap.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Vendor libraries -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.payment/1.2.3/jquery.payment.min.js"></script>
    <script src="js/formKontrolOdeme.js"></script>
    <!-- If you're using Stripe for payments -->
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <link rel="stylesheet" type="text/css" href="css/odeme.css">
</head>
<body>
<?php
require_once "common/header.phtml";
?>

<div class="container">
    <div class="row">
        <!-- You can make it whatever width you want. I'm making it full width
             on <= small devices and 4/12 page width on >= medium devices -->
        <div class="col-md-4">
        </div>
        <div class="col-xs-12 col-md-4" style="margin-top: 15px">


            <!-- CREDIT CARD FORM STARTS HERE -->
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading display-table" >
                    <div class="row display-tr" >
                        <h3 class="panel-title display-td" >Ödeme Bilgileri</h3>
                        <div class="display-td" >
                            <img class="img-responsive pull-right" src="http://i76.imgup.net/accepted_c22e0.png">
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <form role="form" name="frm" id="payment-form" method="post">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="cardNumber">Kart Numarası</label>
                                    <div class="input-group">
                                        <input type="tel" class="form-control" name="cardNumber" id="cardNumber" autocomplete="cc-number" required autofocus/>
                                        <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-7 col-md-7">
                                <div class="form-group">
                                    <label for="cardExpiry"><span class="hidden-xs">Son Kullanma Tarihi</span></label>
                                    <input type="tel" class="form-control" name="cardExpiry" id="cardExpiry" placeholder="AY / YIL" autocomplete="cc-exp" required/>
                                </div>
                            </div>
                            <div class="col-xs-5 col-md-5 pull-right">
                                <div class="form-group">
                                    <label for="cardCVC">CVC</label>
                                    <input type="tel" class="form-control" name="cardCVC" id="cardCVC" placeholder="XXX" autocomplete="cc-csc" required/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="couponCode">Kart Üzerindeki Ad Soyad</label>
                                    <input type="text" class="form-control" id="adSoyad" name="adSoyad" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <button class="subscribe btn btn-success btn-lg btn-block" onClick="checkform()" type="button">Ödeme Yap Ve Satın Al</button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <p class="payment-errors">
                                    <label class="control-label" id="errorLabel" name="errorLabel" style="color: red;"></label>
                                </p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- CREDIT CARD FORM ENDS HERE -->


        </div>


    </div>
</div>

<?php require_once "common/footer.phtml"; ?>
</body>
</html>