
<html>
   <head>
      <title>Profile</title>
       <link rel="stylesheet" type="text/css" href="css/style.css"/>
       <link rel="stylesheet" type="text/css" href="css/menubar.css"/>
       <link rel="stylesheet" type="text/css" href="css/signin.css"/>
       <!-- Bootstrap core CSS -->
       <link href="dist/css/bootstrap.css" rel="stylesheet">

       <!-- Custom styles for this template -->
       <link href="navbar.css" rel="stylesheet">
       <script src="js/jquery-3.1.1.min.js" type="text/javascript"></script>
       <script src="js/menubar.js" type="text/javascript"></script>
   </head>
   <body>
   <?php require_once "common/header.phtml"; ?>
   <div class="container">
       <div class="row">
           <div class="col-xs-12 col-sm-6 col-md-6">
               <div class="well well-sm">
                   <div class="row">
                       <div class="col-sm-6 col-md-4">
                           <?php
                           if($img_url==NULL)
                               $img_url="img/defaultphoto.png";
                           echo " <img src='$img_url' class=\"img-rounded img-responsive\" alt=\"\">"?>
                       </div>
                       <div class="col-sm-6 col-md-8">
                           <h4> <?php echo $firstName." ".$lastName ?></h4>
                           <p>
                               <i class="glyphicon glyphicon-envelope"></i><?php echo $email ?>
                               <br />
                                <label>Kayıt Tarihi: </label>
                               <?php
                               $register_date=date('d.m.Y', strtotime($register_date));
                               echo "$register_date" ?>
                               </p>
                               <label> Telefon Numarası: </label>
                                    <?=$user->phonenumber ?>
                                <br />
                           <!-- Split button -->


                                <?php  require_once __DIR__.'/../controller/session.php';
                                if($_SESSION['id'] == $user->id ) ?>
                           <div class="btn-group">
                               <input type="button" class="btn btn-primary" onclick="window.location.href='update-profile?userid=<?=$id?>'"  value="Profili Düzenle" </input>
                           </div>
                           <div class="btn-group">
                               <input type="button" class="btn btn-primary" onclick="window.location.href="   value="Mesaj Gönder" </input>
                           </div> </br>



                           <a href='<?php
                                    require_once __DIR__.'/../model/Constants.php';
                                    echo Constants::$serverUrl;
                                        ?>'>AnaSayfaya Dön</a>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>
   </body>
</html>
