
<html>
   <head>
      <title>Profile</title>
   </head>
   <body>
   <table>
       <tr>
           <td><label>Adı:</label><?php echo $firstName ?></td>
       </tr>
       <tr>
           <td><label>Soyadı:</label><?php echo $lastName ?></td>
       </tr>
       <tr>
           <td><label>Email:</label><?php echo $email ?></td>
       </tr>
       <tr>
           <td><a href="index.phtml">Anasayfaya Dön</a></td>
       </tr>
   </table>
   </body>
</html>
