<html>
<head>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="dist/css/bootstrap.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>
<?php
require_once "../controller/session.php";
require_once "common/header.phtml";
require_once "../model/Category.php";
?>
<div id="sell-form-content">
    <table align="center">
        <tr id="categoryRow">
            <td>Ürün Kategorisi:</td>
            <td><select size='10' id="firstCategory">
                    <option value="">Kategori Seçiniz..</option>
                    <?php $menus = Category::getCategoryByParentId(0);
                    while ($menu = mysqli_fetch_array($menus)) {
                        echo "<option value='" . $menu["id"] . "'>" . $menu["name"] . "</option>";
                    }
                    ?>
                </select>
            </td>
        </tr>
    </table>

</div>
<script type="text/javascript">
    $('#firstCategory').change(function () {

        $('#secondCategory').remove();
        $('#thirdCategory').remove();

        var selectedFirst = $('#firstCategory').val();
        $.post("<?php require_once "../model/Constants.php";
                echo Constants::$serverUrl; ?>/controller/getCategoryByJSON.php",
            {
                id: selectedFirst
            },
            function (data) {
                var json = jQuery.parseJSON(data);
                var i = 0;
                var htmlOptions = "<select size='10' id='secondCategory'>";
                while (i < json.length) {
                    htmlOptions += "<option value='" + json[i].id + "'>" + json[i].name + "</option>";
                    i++;
                }
                htmlOptions+="</select>";


                $('#categoryRow').append(htmlOptions);
            });
    });
    $('body').on('change','#secondCategory',function () {

        $('#thirdCategory').remove();

        var selectedSecond = $('#secondCategory').val();

        $.post("<?php require_once "../model/Constants.php";
                echo Constants::$serverUrl; ?>/controller/getCategoryByJSON.php",
            {
                id: selectedSecond
            },
            function (data) {
                var json = jQuery.parseJSON(data);
                var i = 0;
                var htmlOptions = "<select size='10' id='thirdCategory'>";
                while (i < json.length) {
                    htmlOptions += "<option value='" + json[i].id + "'>" + json[i].name + "</option>";
                    i++;
                }
                htmlOptions+="</select>";
                $('#categoryRow').append(htmlOptions);
            });
    });
</script>
</body>
</html>