<html>
<head>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="dist/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="css/sell_products.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>
<?php
require_once "../controller/session.php";
require_once "common/header.phtml";
require_once "../model/Category.php";
require_once "../model/Constants.php";

    if(!$_SESSION['isLogged']){
        header('Location: '.Constants::$serverUrl."/login");
    }
?>



<div id="content">
    <div class="container">

        <div id="sell-form-content">
            <div class="col-md-12">
                <center><h2>Satmak İstediğiniz Ürünün Kategorisini Seçiniz</h2></center><hr>
                <div class="form-group">
                    <table align="left">

                        <tr id="categoryRow">
                            <td><select class="form-control" size='19' id="firstCategory" style="background-color: crimson; color:white; overflow: hidden;">
                                    <?php $menus = Category::getCategoryByParentId(0);
                                    while ($menu = mysqli_fetch_array($menus)) {
                                        echo "<option style=\"margin-top: 30px; \" value='" . $menu["id"] . "'>" . $menu["name"] . "</option>";
                                    }
                                    ?>
                                </select>
                            </td>
                        </tr>
                    </table>
                </div></div>
        </div>
    </div>
</div>
<script type="text/javascript">

    var ProductCategoryID;

    $('#firstCategory').change(function () {

        $('#secondCategory').remove();
        $('#thirdCategory').remove();
        $('#btnContinue').remove();

        var selectedFirst = $('#firstCategory').val();
        $.post("<?php require_once "../model/Constants.php";
                echo Constants::$serverUrl; ?>/controller/getCategoryByJSON.php",
            {
                id: selectedFirst
            },
            function (data) {
                if (data === 'no such category') {
                    ProductCategoryID = selectedFirst;
                    addContinue();
                }
                else {
                    var json = jQuery.parseJSON(data);
                    var i = 0;
                    var htmlOptions = "<select class='form-control' size='19' id='secondCategory' style='background-color: crimson; color:white; overflow: hidden;'>";
                    while (i < json.length) {
                        htmlOptions += "<option style='margin-top: 30px;' value='" + json[i].id + "'>" + json[i].name + "</option>";
                        i++;
                    }
                    htmlOptions += "</select>";

                    $('#categoryRow').append(htmlOptions);
                }
            });
    });
    $('body').on('change', '#secondCategory', function () {

        $('#thirdCategory').remove();
        $('#btnContinue').remove();

        var selectedSecond = $('#secondCategory').val();

        $.post("<? echo Constants::$serverUrl; ?>/controller/getCategoryByJSON.php",
            {
                id: selectedSecond
            },
            function (data) {
                if (data === 'no such category') {
                    ProductCategoryID = selectedSecond;
                    addContinue();
                }
                else {
                    var json = jQuery.parseJSON(data);
                    var i = 0;
                    var htmlOptions = "<select class='form-control' size='19' id='thirdCategory' style='background-color: crimson; color:white; overflow: hidden;'>";
                    while (i < json.length) {
                        htmlOptions += "<option style='margin-top: 30px;' value='" + json[i].id + "'>" + json[i].name + "</option>";
                        i++;
                    }
                    htmlOptions += "</select>";

                    $('#categoryRow').append(htmlOptions);
                }
            });
    });
    $('body').on('change', '#thirdCategory', function () {
        var selectedThird = $('#thirdCategory').val();
        ProductCategoryID = selectedThird;
        addContinue();
    });
    function addContinue() {
        var btnContinue = "<input id='btnContinue' type='button' value='Devam'/>"
        $('#categoryRow').append(btnContinue);
    }
    $('body').on('click', '#btnContinue', function () {
        $('#sell-form-content').remove();
        $('#content').load("view/sell-products-content/product-details.html");
    });
    $('body').on('click','#btnSell', function () {
        var name=$('#product_name').val();
        var price=$('#product_price').val();
        var image_url=$('#product_image').val();

        $.post("<?php require_once "../model/Constants.php";
            echo Constants::$serverUrl; ?>/controller/insertProduct.php",
            {
                name: name,
                price: price,
                category_id: ProductCategoryID,
                brand_id: 0,
                seller_id: <? echo $_SESSION['id']?>,
                image_url: image_url
            },function (data) {
                alert(data);
            }
        )

    })
</script>
</body>
</html>