<html xmlns="http://www.w3.org/1999/html">
<head>
    <title>Kayıt Ol</title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="js/signinControl.js"></script>
    <script src="js/submit.js"></script>

</head>
<body>
<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '1321780007845681',
            xfbml      : true,
            version    : 'v2.8'
        });
        FB.AppEvents.logPageView();
    };
    function myFacebookLogin() {
        FB.getLoginStatus(function(response) {
            if (response.status === 'connected') {
                console.log('Logged in.');
                FB.api(
                    '/me',
                    {fields: 'id,first_name,last_name,email'}, function(response){

                        //Post edilecek parametreler
                        params = new Array();
                        params["firstName"] = response.first_name;
                        params["lastName"]=response.last_name;
                        params["email"]=response.email;
                        params["password"]=null;
                        params["facebookID"]=response.id;
                        params["signType"]="fb";

                        //Javascript kullanarak post yapan method..
                         submit("login",params,"post");
                    });
            }
            else {
                FB.login(function(response){
                }, {scope: 'public_profile,email'});
            }
        });
    }
    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));


</script>
<div class="authForm">

    <h1 class="authBaslik">Kayıt Ol</h1>
    <div class="faux-fb-btn">
        <button onclick="myFacebookLogin()">Facebook ile giriş yap</button>
    </div>
    <h5>veya</h5>
    <form name=frm method="post" action="signin">
    <table>
        <tr>
            <td><label>Adınız:</label></td>
            <td><input class="txtBox" type="text" name="firstName" id="txtfirstName" placeholder="firstname"></td>
        </tr>
        <tr>
            <td><label>Soyadınız:</label></td>
            <td><input class="txtBox" type="text" name="lastName" id="txtlastName" placeholder="lastname"></td>
        </tr>
        <tr>
            <td><label>E-posta adresiniz:</label></td>
            <td><input class="txtBox" type="email" name="email" id="txtEmail" placeholder="e-mail"></td>
        </tr>
        <tr>
            <td><label>Şifreniz:</label></td>
            <td><input class="txtBox" type="password" name="password" id="txtPassword" placeholder="password"></td>
        </tr>
        <label style="color: red" id="lblErrorPassword" name="lblErrorPassword"></label>
        <tr>
            <td><label>Şifreniz (Tekrar):</label></td>
            <td><input class="txtBox" type="password" name="passwordAgain" id="txtPasswordAgain" placeholder="password (Again)"></td>
        </tr>
        <tr>
            <input type="hidden" name="signType" value="form"/>
            <td><a href="../index.php"><label>Anasayfaya Dön</label></a></td>
            <td><input type="button" name="btnSignin" value="Kayıt Ol" onClick="checkform()"></td>
        </tr>
    </table>
</form>
</div>
</body>
</html>
